// <auto-generated />
namespace _555Lottery.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _555Lottery_20130723d : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_555Lottery_20130723d));
        
        string IMigrationMetadata.Id
        {
            get { return "201307232027376_555Lottery_20130723d"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
