// <auto-generated />
namespace _555Lottery.DataModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _555Lottery_20131202a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_555Lottery_20131202a));
        
        string IMigrationMetadata.Id
        {
            get { return "201312021612049_555Lottery_20131202a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
