// <auto-generated />
namespace _555Lottery.DataModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _555Lottery_20130909a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_555Lottery_20130909a));
        
        string IMigrationMetadata.Id
        {
            get { return "201309091338303_555Lottery_20130909a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
