//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _555Lottery.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_555Lottery.Service.Resources.EmailTemplates", typeof(EmailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html style=&quot;height: 100%; display: table; margin: auto;&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Draw report - @Model.Draw.DrawCode&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;height: 100%; display: table-cell; vertical-align: middle; background-color: #000000; color: #8dd9ff;&quot;&gt;
        ///    &lt;div style=&quot;width: 960px; z-index: 50;&quot;&gt;
        ///        &lt;div id=&quot;biglogo&quot; style=&quot;display: block; margin: 44px 100px 0px 100px; width: 780px; height: 156px;&quot;&gt;
        ///            &lt;img runat=&quot;server&quot; src=&quot;http://beta.555lottery.com/Content/images/555_lottery_logo.png&quot; alt= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TEST_BODY {
            get {
                return ResourceManager.GetString("TEST_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw report - @Model.Draw.DrawCode.
        /// </summary>
        internal static string TEST_SUBJECT {
            get {
                return ResourceManager.GetString("TEST_SUBJECT", resourceCulture);
            }
        }
    }
}
